### entry point for the script
get http://localhost:3000/api/

### get all users
get http://localhost:3000/api/users

### get user by id
get http://localhost:3000/api/users/621d3abd37b01d44ca43cafc

### post a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Otro mas",
  "email": "otro@gmail.com",
  "password": "12345678",
  "avatar": "https://avatars2.githubusercontent.com/u/1234?v=3&s=456",
  "whatsapp": "09123456789",
  "bio": "I am a junior developer"
}

### update user
PUT http://localhost:3000/users/621d3abd37b01d44ca43cafc
Content-Type: application/json

{
  "name": "Juan Fco Losa Marquez",
  "email": "juanfril@gmail.com",
  "password": "12345678",
  "avatar": "https://avatars2.githubusercontent.com/u/1234?v=3&s=460",
  "whatsapp": "5555555",
  "bio": "I'm a software developer"
}

### delete a user
delete http://localhost:3000/users/621d3abd37b01d44ca43cafc