import '../styles/globals.css';
import Head from 'next/head';
import { AuthProvider } from '../components/Auth';
import Navbar from '../components/nav';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Luthier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthProvider>
        <Navbar />
        <Component {...pageProps} />
      </AuthProvider>
    </>
  );
}

export default MyApp;
